services:
  server:
    container_name: server
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  # client:
  #   container_name: client
  #   restart: always
  #   build:
  #     context: ./client/
  #     dockerfile: Dockerfile
  #   ports:
  #    - 5173:5173