services:
  web-comm-api:
    container_name: web-comm-api
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  web-comm-client:
    container_name: web-comm-client
    restart: always
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
     - 3000:3000